### ISSUE TITLE
error while running the file

### ISSUE THREAD

**Issue by guy111a** [targetblank/micropython_ahtx0#2]
Hello

connected the aht10 to pi pico, saved 2 files and run the example, i get the next error:
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
TypeError: 'id' argument required

i can see the address "0x38" of the sensor with i2c scanner.

i was trying to understand what is the missing ID .. but cannot, please help !
Thank you

**Comment by guy111a** [comment]
ok, found it.

i2c = I2C(0, scl=Pin(1), sda=Pin(0))   # added 0,

**Comment by targetblank** [comment]
Seems like the machine.I2C constructor behaves a bit different on Pi Pico compared to the ESP8266 boards (where I tested the example). Closing this issue...
